// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0TPTjkUaHhLmT8CMYQEVPgQFnT8G1E7s',
    appId: '1:153341749063:web:2e1507973c13cb59cc8e62',
    messagingSenderId: '153341749063',
    projectId: 'grproject-30463',
    authDomain: 'grproject-30463.firebaseapp.com',
    databaseURL: 'https://grproject-30463-default-rtdb.firebaseio.com',
    storageBucket: 'grproject-30463.firebasestorage.app',
    measurementId: 'G-1DKM2CPSPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqCEobgkDpeIgsjJ1amqmlN__c16DUWWg',
    appId: '1:153341749063:android:fdcb4fc7b37107efcc8e62',
    messagingSenderId: '153341749063',
    projectId: 'grproject-30463',
    databaseURL: 'https://grproject-30463-default-rtdb.firebaseio.com',
    storageBucket: 'grproject-30463.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvdE8fHzvWoL1jhTkGWSS--RwpQdV9rOk',
    appId: '1:153341749063:ios:f92b7e63d768dcd9cc8e62',
    messagingSenderId: '153341749063',
    projectId: 'grproject-30463',
    databaseURL: 'https://grproject-30463-default-rtdb.firebaseio.com',
    storageBucket: 'grproject-30463.firebasestorage.app',
    iosBundleId: 'com.example.grproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvdE8fHzvWoL1jhTkGWSS--RwpQdV9rOk',
    appId: '1:153341749063:ios:f92b7e63d768dcd9cc8e62',
    messagingSenderId: '153341749063',
    projectId: 'grproject-30463',
    databaseURL: 'https://grproject-30463-default-rtdb.firebaseio.com',
    storageBucket: 'grproject-30463.firebasestorage.app',
    iosBundleId: 'com.example.grproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0TPTjkUaHhLmT8CMYQEVPgQFnT8G1E7s',
    appId: '1:153341749063:web:c76c029aaf30641acc8e62',
    messagingSenderId: '153341749063',
    projectId: 'grproject-30463',
    authDomain: 'grproject-30463.firebaseapp.com',
    databaseURL: 'https://grproject-30463-default-rtdb.firebaseio.com',
    storageBucket: 'grproject-30463.firebasestorage.app',
    measurementId: 'G-4XK015FTQX',
  );

}